### ISSUE TITLE
extra page

### ISSUE THREAD

**Issue by lanox** [kc0bfv/autophugo#10]
Hi 

Sorry I have another question, I was wondering is it possible to create an additional page as you have "About"   but without contact form, etc just a page that you could add some text such as Camera equipment I use etc, and either to open as halfway as about section or to open in a new page.

I dunno if you think it's a good idea.

Thanks

lp

**Comment by kc0bfv** [comment]
You can customize the about page to remove the contact form, then put other content there, or link to other pages from the about page.  Other, non-photo pages would probably use some other Hugo theme...

**Comment by kc0bfv** [comment]
Hrm, actually, looks like that ability is not well documented.  I'll add some documentation about how to do that

**Comment by lanox** [comment]
Thanks much appreciate all the effort @kc0bfv and sorry for all the questions.

**Comment by kc0bfv** [comment]
Hey!  Documentation added to the Readme.  I'm gonna leave this open so I remember to also try to consolidate some of the subsection / subalbum / noalbum rendering code.  And to maybe implement optional weighted sorting at that time.  That would let you do the other thing you want to do.  I still don't like the other thing you want to do ;-)  But that's ok - I think this will result in cleaner code and a simpler setup, and also fix your problem ;-)

**Comment by kc0bfv** [comment]
And - I consolidated the subalbums and noalbums now.  You can get it to render images and subalbums at the same level now.  "dogs" album is an example - the important part is in the assets dir...
