### ISSUE TITLE
Display logo in the nav bar

### ISSUE THREAD

**Issue by fabrizio2210** [kc0bfv/autophugo#15]
Hi,
I am wondering if a logo in the navbar is in the roadmap of this theme.

I think it can complete the intention of identifying the author, placing it close to the name in the bar. 

I tried to insert it to show you (see bottom bar logo+name):
![image](https://user-images.githubusercontent.com/34220075/111882497-3a4b5200-89b6-11eb-8a01-693cbbeff246.png)

**Comment by kc0bfv** [comment]
I'm not planning to add something like that - but you definitely can for your specific sites...  You can modify the layouts/partials/header.html file and insert that img right before the "h1" tag and all the stuff in there.  You might have to play with some of the other CSS for your new img and some of the other parts too, to get it how you want.

In your hugo site, Hugo will let you create your own version of that header partials layout file.  You'd use/create a layouts directory in your site's main directory (not in "theme"), and use/create a partials directory in there, then copy the theme "header.html" file into your site's layouts/partials directory.  Hugo will choose to use that file first, and skip the theme one.

That way even if you update the theme later on you'll still keep your version of the header file.
