### ISSUE TITLE
Add a configuration option to disable « Download » feature in image details 

### ISSUE THREAD

**Issue by MrRaph** [kc0bfv/autophugo#22]
I’m using your beautiful theme but I don’t want my users to be able to download my pictures. 
I disabled this feature using an ugly way by tweaking JS files. 

May be adding a configuration toggle to disable it could be a good thing ?

**Comment by kc0bfv** [comment]
Thanks @fabrizio2210!  Yes.  Integrated as config option now.

**Comment by MrRaph** [comment]
Thank you so much, this is awesome as well !!! 👍
