### ISSUE TITLE
Sorting Images in album?

### ISSUE THREAD

**Issue by whereiswhere** [kc0bfv/autophugo#25]
Is there a way to sorting images in an album? Like 10.jpeg > 09.jpeg > 08.jpeg ... ? 

Ask this because I wish put the newest images first and I can't find how to do it.

**Comment by kc0bfv** [comment]
I think it's sorted by filename, opposite of how you want it.  There may be a way to change line 56 in layouts partials sect_and_img_content such that it orders in some other way, like by date.  I think you could also just reverse the list and get images in opposite order...

**Comment by whereiswhere** [comment]
> I think it's sorted by filename, opposite of how you want it. There may be a way to change line 56 in layouts partials sect_and_img_content such that it orders in some other way, like by date. I think you could also just reverse the list and get images in opposite order...

Thanks for replying. I've work it out by add some parameter in the sect_and_img_content file.
