### ISSUE TITLE
More than two Columns

### ISSUE THREAD

**Issue by adriandiver** [kc0bfv/autophugo#3]
Hi Karl,

great work - thank you. Is it possible to set more than two columns for the gallery? 

I digged a little bit deeper into it and found a param called column_count. If I set it to any number it does not change the overall gallery experience. Could you give me a hint how I can change it?

Thanks,
Adrian

**Comment by kc0bfv** [comment]
Adrian,
It doesn't work yet, you're right.  I plan to put that in as a feature, but
when I looked at how I'd do that it required some serious reworking.

I'm planning to tackle it at the same time I add the pictures in from left
to right (currently they're oriented in columns).  That would make keyboard
accessibility work more nicely...

I think this should be possible with flexbox, but haven't sat down to
figure it out.  The trick is to get it to still look like columns.

Regardless, that change might make it easier to implement the varied column
count.  So I've held off.

It might take me a bit of time to get to this one, like a couple months.
If you make it work in the meantime please let me know.

-Karl

**Comment by adriandiver** [comment]
Karl, 
many thanks for your feedback. I'll try to figure it out and create a pull request in case I find a suitable solution. Have a great time and talk soon,
Adrian

**Comment by kc0bfv** [comment]
I think the fix will work for any number of columns, based on the way flexbox columns work.  Then - I added some test data in a gallery - just 100 images of words that start with J - but enough to play around with column counts and see how they change.

**Comment by kc0bfv** [comment]
I gave up on the other flexbox method a while ago because I realized the vertical offsets between images in different columns were not solvable in a sensible way.  The content is organized in columns - so I won't fight it :-)  Unfortunately accessibility suffers in-that the image tab order and keyboard order is top-bottom left-right in the code.  Oh well.
