### ISSUE TITLE
_index.md creation - file empty

### ISSUE THREAD

**Issue by pokemonbattledroid** [kc0bfv/autophugo#38]
Hi,
Clearly doing something wrong, but I've made an 'assets' folder with folders inside it with jpgs.

So my project folder is **travel**
travel/location/*.jpgs
travel/location2/*.jpgs
...

From terminal I run **hugo new location/_index.md**, I get a new _index.md file in **travel/content/location**, but it's just the top bits and no content, depsite the assets folder having images.

---
title: "Location"
date: 2022-02-28T17:23:13Z
draft: true
---

Any help is appreciated, this looks like an amazing platform to do what I'm hoping to do.

Thank you so much!!

**Comment by kc0bfv** [comment]
Hrm...  I'm not 100% clear on what your directory structure looks like - but if you look at the `exampleSite` directory you'll see how it needs to look.  Walking through a new hugo site, you'd run:

`hugo new site travel`

Then you'd have a new directory called `travel`, with the following contents:

archetypes
config.tml
content
data
layouts
static
themes

You need to create an `assets` directory in there too.  Then you'd create subdirectories of that, location and location2.  It'll look like:

archetypes
assets
assets/location
assets/location2
config.tml
content
data
layouts
static
themes

Then put your photos in those assets/location and assets/location2 directories.

Then, *from within the base `travel` directory*, running `hugo new location/_index.md` and `hugo new location2/_index.md` and `hugo new _index.md` will give you the following:

archetypes
assets
assets/location/image.jpg
assets/location2/image2.jpg
config.tml
content
content/_index.md
content/location/_index.md
content/location2/_index.md
data
layouts
static
themes

And of course you need to have the theme in `themes`...  But that should be the directory structure you need to get this to work.  It's the same as in the exampleSite.

**Comment by pokemonbattledroid** [comment]
I'll give that a go! Thanks for the thorough tutorial!

**Comment by kc0bfv** [comment]
Closing pending other feedback.
