### ISSUE TITLE
Option to not resize full images

### ISSUE THREAD

**Issue by not-napoleon** [kc0bfv/autophugo#39]
Hello and thank you for your work on this project.  I am an amateur photographer looking to use Autophugo & Hugo to set up a small gallery page.  While the automatic resizing for thumbnails is a huge help, I already export my full sized images from Lightroom in the dimensions and resolution I want, so no further processing is necessary.  I'd rather just show them exactly as I exported them.

I'm working around this now by setting the resize method to "Fit" and setting a very large size, but it would be easier for me to just skip the resize step entirely for my final images.  

Thank you!

**Comment by kc0bfv** [comment]
Easy peasy.  Good idea.  Done & documented - use "none" instead of "fit" in "full_resize_method".
