### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by comstock** [kc0bfv/autophugo#45]
Any advice on how to resolve the following issue? Is it a failed SHA-256 mismatch? The following is pasted log from Chrome inspection.

```
index.html:22 Failed to find a valid digest in the 'integrity' attribute for resource 'https://[...]/moby/css/custom.min.0a714016e6cd2c76e9fb635896a34e8376e360f2cab147593f0486dc95cd9d37.css' with computed SHA-256 integrity '2/3hYasl9XNsi9knnAEy/+EIvNgbxen9tJzZDvrjeRE='. The resource has been blocked.
index.html:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```

**Comment by kc0bfv** [comment]
Yes, at least that first error looks like a SHA-256 mismatch.  Could you share the site where you're seeing this?  I'm not seeing it when testing.  The theme tells hugo to combine several different CSS files into one, minimize it, and package that as the custom.css, then hugo calculates the hash and puts both into the HTML file output.  If custom.css is getting changed after Hugo does its thing, that could be causing your problem.  A number of different things could be changing it - but probably not hugo or the theme itself.

**Comment by comstock** [comment]
https://comstock.cc/moby/index.html

(Thanks)

**Comment by comstock** [comment]
I am using GGL Cloud for hosting. I made a configuration change this morning, and had the same error, but a few hours later, the checksums matched. I think it may be a caching issue with the browser, maybe. I will mark this as resolved. Thanks.

**Comment by kc0bfv** [comment]
Thanks for the update!  I was looking at it on my phone this morning but
couldn't reproduce, and figured either mobile wasn't reporting the issue or
it was a caching issue somewhere.
