### ISSUE TITLE
Workaround for identifying albums

### ISSUE THREAD

**Issue by wwone** [kc0bfv/autophugo#48]
I am getting used to using this theme with HUGO, and am more and more happy.

One issue mentioned in GitHub is how it is hard to identify albums and
sub-albums.

"On 23 Jan 2020 subalbum and noalbum support no longer requires specifying a type in the metadata. Furthermore, images and subalbums can be mixed within albums - including on the homepage (although mixing can be confusing for users)."

I have worked around it by creating images that are narratives and identifiers for
the sub-albums.

Please see:

http://swansongrp.com/P/food

I am continuing to update my website with autophugo work, rather than the many
other approaches taken over the years for photo display.

Keep up the good work!

**Comment by kc0bfv** [comment]
That works pretty well!  Nice albums!
