### ISSUE TITLE
Some Changes are Processed Immediately, Others Require Removal of "resources" and "public" and Rebuild

### ISSUE THREAD

**Issue by wwone** [kc0bfv/autophugo#49]
I've started to notice that when I make some changes to my tree of files that the changes appear immediately (while running "hugo server" btw). Other changes, particularly adding metadata to images (title, etc) do not appear unless I perform a complete rebuild of the tree. In order for the rebuild to work properly, I have discovered that I have to completely erase "resources" and "public" before running "hugo".

With the processing time needed for image handling, this become quite a long wait for a few changes. And, if I discover that I made a typo in one of the image titles, the whole process has to be repeated.

Is there any reasonable way to deal with these types of changes without a cleanup and full rebuild?

**Comment by kc0bfv** [comment]
I don't have this problem...  Running `hugo server` just now on the exampleSite I can edit the `content/cats/_index.md` file and add or change metadata, or in `content/dogs/pensive-dog/_index.md` I can create metadata for dog_07 (which didn't have any) and in all cases `hugo server` picks it up, regenerates the necessary HTML files, and reloads my browser showing the correct content.  I don't have to wait for images to reprocess.

**Comment by wwone** [comment]
I will try to reproduce the workflow that causes this. I think that the removal, replacement, or external addition of photos seem to trigger the requirement. I see it especially when using the local server (the page behavior is often different between local test server and production site...). My somewhat vague problem description is not beneficial, so I need to sharpen up the workflow and determine when complete re-creation has to take place.

**Comment by kc0bfv** [comment]
Occasionally I've run into instances like what you describe too, but I
think they felt more like Hugo bugs than theme bugs, and trying to
reproduce it running a recent version of Hugo I had no luck...

**Comment by kc0bfv** [comment]
Closing for lack of further info.
