### ISSUE TITLE
Google indexes only the 'albumthumb' and not all pictures

### ISSUE THREAD

**Issue by h0lad** [kc0bfv/autophugo#52]
Hi!

I really love using your theme! It's great on desktop and smartphones/tablets.

But it seems that at least Google is having big problems indexing the pictures and their description. 

It's only catching the albumthumb and not the rest of the pictures at the moment.

What would be the easiest way to improve this?

Thank you!

**Comment by kc0bfv** [comment]
Thanks!  (sorry for this delay)

If I Google `site:https://kc0bfv.github.io/autophugo/`, for instance, I see the alt text from individual pictures listed under page links.  Then, clicking "images" I see some of the images from the album, and when I click them I see the large version of the image.

Not sure what the problem with the images might be - I definitely don't see all the images from the albums in there, but I see many of them.  Some of that may be some algorithm Google uses.  Not sure what we could do to improve on that part.

I don't see the image descriptions in the Google results though...  And while I can search for the alt text I cannot search and find the descriptions.  Those don't seem to get crawled.  Those are stored as an attribute on the `a` tag until you click the image, when it gets displayed as a figure and figure caption.  Doing a little SEO reading, I think I can put the image descriptions in next to each thumbnail as a `display:none` element, and google will crawl them, and determine that they refer to the image.  Will try that...

**Comment by kc0bfv** [comment]
I do believe that has fixed it.
