### ISSUE TITLE
Hello, please ask a question, I how to change the website title display mode to logo picture.

### ISSUE THREAD

**Issue by heihahehe** [kc0bfv/autophugo#55]
![20231205160855](https://github.com/kc0bfv/autophugo/assets/152707762/0ce93b66-498e-4271-8fa6-f70f0f7ef37a)

**Comment by heihahehe** [comment]
And how do I refer to the logo img address in the toml Settings if I use header.html.
![20231205162545](https://github.com/kc0bfv/autophugo/assets/152707762/520507b4-a563-4776-b606-3fc3770df857)

**Comment by kc0bfv** [comment]
That's not a feature currently.  Plus, that spot gets used as a breadcrumb for location when people browse albums and subalbums.

If you really want that to be a logo, you probably just want to fork this and modify the code to do that for you.
