### ISSUE TITLE
quesion about albums

### ISSUE THREAD

**Issue by lanox** [kc0bfv/autophugo#9]
Hi, 

Thanks for the theme it's great, I was wondering if it's possible to have one level albums support?

basically, I would like to have an image showing on the main page and when you click on it will zoom in?

Thanks

**Comment by kc0bfv** [comment]
Hey @lanox - glad you like it!  I think I just added it - called "no-album support".  Now, if you download, and `make serverNoAlbum`, or just look in `exampleSiteNoAlbum` and see how to make your own, I think it's what you're asking for.

**Comment by lanox** [comment]
WOW
thanks you are a gun :)

One more question, I find album cover pictures to be blurry is that by design? or am I doing something wrong

**Comment by kc0bfv** [comment]
Hope it works for you 😁

Re: blurry, if you modify thumb_quality and thumb_width it may help.  Those can trade-off between quality and size.  They are described in the readme.

**Comment by lanox** [comment]
Yeah, I have read it and tried it, but didn't seem to make much difference, will try again, maybe I have foobared something.

**Comment by kc0bfv** [comment]
It seems to work here - make sure you're changing it in the `params` area of the config for the whole site.  There's an example in the `exampleSite/config.toml` file, with the defaults filled in.  When I uncomment those, and change them to match the `full_` settings, it updates as expected.

**Comment by lanox** [comment]
Hey @kc0bfv  

Sorry to bother you again, I was wondering is there a chance to have albums and not albums together. 

I tried adding structure from exampleSite  and it doesn't seem to work.
Thanks

**Comment by kc0bfv** [comment]
So, you're thinking the front page would be a mix of photos and albums, some you'd click on and get a photo pop up, and some you'd click on and get redirected to an album?  I think that'd be confusing for users.  I'd think one extra album containing the "non-album" photos would provide a consistent user interface.

**Comment by lanox** [comment]
```So, you're thinking the front page would be a mix of photos and albums```  Yes that is exactly right, and the beautiful think about this is that you already can give the name to the album, therefor can be less confusing.

**Comment by lanox** [comment]
My theory behind this is I could group photos for a specific project/scenery and if some random single photos don't need to be part of the album I could just put them on the front page rather creating another random album.

**Comment by lanox** [comment]
any further thoughts on this?

**Comment by kc0bfv** [comment]
I think if I combine some parts of the code it'll work for you.  Just haven't had time to do it yet.  Keeping the other issue open to track this.
